{% set name = "array_split" %}
{% set version = "0.6.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.zip
  sha256: "267953eb84808a70bba631a5ca1d516cfbb732d6e03ffbf7fa979c4f3ca69673"

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python {{ 3.8 }}
    - pip
    - setuptools
    - versioneer
  run:
    - python >={{ 3.8 }}

test:
  imports:
    - array_split
  requires:
    - setuptools
    - numpy

about:
  home: https://github.com/array-split/array_split
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'Python package for decomposing multi-dimensional arrays into sub-arrays (slices) according to multiple criteria.'
  description: |
    The array_split python package is an enhancement to existing numpy.ndarray
    functions, such as numpy.array_split, skimage.util.view_as_blocks and
    skimage.util.view_as_windows, which sub-divide a multi-dimensional array
    into a number of multi-dimensional sub-arrays (slices).
  doc_url: https://array-split.readthedocs.io/en/stable/
  dev_url: https://github.com/array-split/array_split

extra:
  recipe-maintainers:
    - ma-sadeghi
